let a=50;
let b=70;
console.log(a+b);
console.log(typeof(a));
document.write(a+b);
let c = "nishi";
console.log(typeof(c));
// alert("this is your first page");
// prompt("Enter a number");
let address = true;
console.log(address);
console.log(typeof(address));
let hi=null;
console.log(hi);
let d=[1,2,3,4,5];
console.log(d);
console.log(typeof(d));
prompt("Enter your name");
alert("this is your first page");
confirm("This is you");